debug: false

# todo : 엑츄에이터의 엔드포인트 중에 감춰져있는 것들을 활성화 시켜주는
management:
  endpoints:
    web:
      exposure:
        include: "*"


logging:
  level:
    com.example.first-board: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  application:
    name: first-board
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: jj
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  #    url: jdbc:h2:mem:testdb
  #    username: sa
  #    password:
  #    driver-class-name: org.h2.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    #    open-in-view: false
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  sql:
    init:
      mode: always



#  h2:
#    console:
#      enabled: false
#  sql.init.mode: always
#  data:
#    rest:
#      base-path: /api
#      detection-strategy: annotated
